apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    # This label is required by kube-prometheus-stack to allow it to
    # create PodMonitor and ServiceMonitor resources in this namespace.
    app.kubernetes.io/managed-by: helm
